### ISSUE TITLE
Can I use `2` instead of `1` for packages/appsets in my config file?

### ISSUE THREAD

**Issue by brianjmurrell** [nikgapps/config#10094]
https://github.com/nikgapps/config/blob/67663adc152499ae8d9010ce67dd599b85fa4c92/README.md?plain=1#L36-L37 says I can only use `1` or `0` but generally that config file allows for `2` also to indicate not to remove an AOSP package.

Can I actually use `2` instead of `1` in my config file that I push in a PR here or can I only use `1` and I will have to modify the config in the generated ZIP when I download it?

**Comment by nikhilmenghani** [comment]
Yes you can use 2

**Comment by brianjmurrell** [comment]
Hrm.  This didn't actually seem to work.  I pushed 9ecb0a4 to simply change `1`s to `2`s in my config and the resulting ZIP was much smaller, and missing many packages.

**Comment by nikhilmenghani** [comment]
@brianjmurrell https://github.com/nikgapps/project/commit/41c23c3c60139a9a9aa0d63531b47722bb1f6743 this is fixed now.

**Comment by brianjmurrell** [comment]
Awesome.  I guess I will have to re-push my last PR to be included in the next build round.

**Comment by nikhilmenghani** [comment]
@brianjmurrell are we good to close this issue?
