### ISSUE TITLE
Config NikGapps installing error

### ISSUE THREAD

**Issue by MaxRone7089** [nikgapps/config#10139]
Hey Nik,
I am Max, a veteran user of github. I recently got some config nikgapps zips for my klte(Samsung Galaxy S5 SM-G900K) device.But when it turns to flashing the gapps pack in TWRP, an error occurs named 'Updater process ended with ERROR: 1". I tried multiple times with multiple custom ROM's And packs, but the error persisted. There is no problems in your normal base packages, this error is in the config releases.
 I expect some solution from you.
From, 
MaxRone7089

**Comment by nikhilmenghani** [comment]
can you provide recovery.log file?

**Comment by nikhilmenghani** [comment]
@MaxRone7089 are we good to close the issue?
