### ISSUE TITLE
elite request: creation of elite/14/ionut/

### ISSUE THREAD

**Issue by ionutgherman** [nikgapps/config#10434]
Hello,
My name is Ionut and I'm the maintainer for crDroid for Pixel 8 Series and Pixel 2 Series. I want to apply for elite because I use NikGapps and I recommend them to my users as Gapps and also contributed with some bugs fixing. From the most of Gapps versions, this is the most customizable and Nikhil is a great dev and the community is one of the best.

Hoping to be added to elites.

Thank you,
Ionut

**Comment by nikhilmenghani** [comment]
Closing the issue since access is provided
