### ISSUE TITLE
elite request: creation of 306bobby

### ISSUE THREAD

**Issue by 306bobby-android** [nikgapps/config#10861]
Hey there Nik and team,

It's Bobby, @the306bobby on telegram and maintainer of crDroid redbull pixel series, hoping to start making elite configs. I believe I should qualify as I recommend nikGapps to my users and I've been doing my best to help Nik with things like Call Screening when spoofing with new Pixels. 

Hope all is well and  appreciate the opportunity

**Comment by nikhilmenghani** [comment]
@306bobby-android hey, what folder name would you like me to provide access to? The builds will be uploaded under that named folder in sourceforge.net and you'll have to create a pull request into that folder in config repo to put your elite config.

**Comment by 306bobby-android** [comment]
@nikhilmenghani Hey nik, just 306bobby is fine!
