### ISSUE TITLE
Pixel launcher not working RisingOS 5.1

### ISSUE THREAD

**Issue by QuantumHorizonn** [nikgapps/config#11687]
RisingOS 5.1 try addon config so many thing but not working
![IMG_20240902_232125_050](https://github.com/user-attachments/assets/9b3a3bfb-3f5e-40cc-90af-738a7d67bf01)

**Comment by nikhilmenghani** [comment]
@QuantumHorizonn can you find the stock launcher installed path? 

you can install a build that doesn't have pixel launcher that way stock launcher will load, find that launcher's installed path and share it here.

**Comment by QuantumHorizonn** [comment]
@nikhilmenghani
/system_ext/priv-app/Launcher3Quickstep
when flash gapps with pixel Launcher included 
delete stock launcher but not replace stock launcher and pixel Launcher not appear what i can do now?
