### ISSUE TITLE
Why GMS cannot be battery optimized anymore?

### ISSUE THREAD

**Issue by pixincreate** [nikgapps/config#2760]
I cannot optimize the battery for GMS anymore which is kinda annoying. I don't own a pixel to get GrapheneOS to sandbox that, and I need it for daily use and college work. I used to restrict its battery, but not anymore!

**Comment by nikhilmenghani** [comment]
That is because optimizing gms leads to delays in notifications which was annoying to a lot of users. We plan to bring it back for those who still wishes to proceed ahead with optimizing gms and make it configurable. Stay Tuned! it'll happen soon!

**Comment by pixincreate** [comment]
> That is because optimizing gms leads to delays in notifications which was annoying to a lot of users. 

If is unoptimized by default AFAIK. 

> We plan to bring it back for those who still wishes to proceed ahead with optimizing gms and make it configurable. Stay Tuned! it'll happen soon!


Better give an option in the config file itself.



Also, GMS and playstore need not have `phone` and `activity recognition` permissions in order to work and these permissions cannot be removed at all! Kindly nange it removable.

**Comment by nikhilmenghani** [comment]
Closing this as we already have another issue open -> #2763
