### ISSUE TITLE
Canary core gapps or config release are not installing ...

### ISSUE THREAD

**Issue by samarbilash** [nikgapps/config#2841]
It skip installation due to insufficient specs , but when I ry with clean flash the problem is same .

**Comment by nikhilmenghani** [comment]
@samarbilash installation logs?

**Comment by samarbilash** [comment]
@
[Logs-RMX1941-NikGapps-core-arm64-11-20220214.tar.gz](https://github.com/nikgapps/config/files/8065641/Logs-RMX1941-NikGapps-core-arm64-11-20220214.tar.gz)

**Comment by samarbilash** [comment]
[Logs-RMX1941-NikGapps-core-arm64-11-20220214.tar.gz](https://github.com/nikgapps/config/files/8065645/Logs-RMX1941-NikGapps-core-arm64-11-20220214.tar.gz)

**Comment by samarbilash** [comment]
But stable version installed properly

**Comment by nikhilmenghani** [comment]
@samarbilash, Fixed with https://github.com/nikhilmenghani/build/commit/e049080dec6650cb48a47e6fcd234b02cfb4403f
please try tonight's canary and let me know if that works for you

**Comment by samarbilash** [comment]
Thanks it working perfectly
