### ISSUE TITLE
NikGApps doesn't support back-tracking of GApps and it's package? I just ended up in a bootloop

### ISSUE THREAD

**Issue by pixincreate** [nikgapps/config#3420]
I'd a `config` version of GApps dated `22-Feb-2022 18:22`. Today, I flashed `Flipendo` and `Pixel Launcher` of date `21-Apr-2022`. The device straight went into bootloop.

I even tried to `uninstall` those packages by re-naming them into `UnInstall.zip` which worked as intended. However, the device didn't boot.

For your reference, I've attached the entire NikGApps Logs folder.
[Logs.zip](https://github.com/nikgapps/config/files/8540488/Logs.zip)

**Comment by nikhilmenghani** [comment]
@pixincreate is there any issue with Bootloop? are we good to close this issue?

**Comment by pixincreate** [comment]
Haven't tried that since then fearing bootloop.

Maybe in future of someone tries and gets stuck might comment here or open a new issue.

Closing as of now.
