### ISSUE TITLE
Pixel launcher keeps crashing on LOS 19.1 Official 

### ISSUE THREAD

**Issue by pixincreate** [nikgapps/config#3455]
I couldn't get the logs as it kept crashing leaving me on lockscreen

Even flipendo crashes

**Comment by pixincreate** [comment]
ok, I checked the addon files in the releases section for canary, many apps do not exist like launcher and stuffs. Are they not supported yet?

**Comment by nikhilmenghani** [comment]
Did you check the stable release addon folder? Which is the addon that you're looking for?

**Comment by pixincreate** [comment]
Yea, 
- I tried installing Canary version along addons, they failed.
- I then tried Configs which you can see it already (LOL) in the pull requests, they again failed for unknown reasons.

> Did you check the stable release addon folder?

And today, again, I flashed a config version, then flashed Addon for Pixel launcher from stable reeases which finally worked like a charm. However, Flipendo still crashes upon selecting on the settings.

>  Which is the addon that you're looking for?

Flipendo and Pixel launcher

**Comment by pixincreate** [comment]
>  try the predefined variants like stock and full to confirm

by this, do you mean that I should not even config the package with `nikgapps.config` that exist in `afzc` folder. Last time when I downloaded the `stock` package, I'd skipped unnecessary packages for me, the same crashes had occured.

>  flashing predefined variants will give you an idea if it's an issue with the latest release.

sure. I believe I should not configure the `.zip`

**Comment by pixincreate** [comment]
Another thing that I wanted to mention / note is that, Text select doesn't work for me.

Does it require internet access to work? If yes which app needs to be given. Android System Intelligence or the Pixel launcher itself?

**Comment by happyeggchen** [comment]
I flashed the stock package and crashed again, I'm on Crdroid8 ginkgo

**Comment by ghosh32** [comment]
dk ,pixel launcher keep crashing ,using superior os

**Comment by pixincreate** [comment]
> pixel launcher keep crashing

Use stable latest config version or core that don't have pixel launcher, then flash pixel launcher add-on downloaded separately, it'll work except text select.

**Comment by pixincreate** [comment]
Another thing for users to keep in mind is that text select partially works, meaning, it detects the texts but cannot let the user copy from it. However, it's not the same with image or links, they work pretty fine.

**Comment by pixincreate** [comment]
Another update from my side:

As of now, at least for me though, pixel launcher works without any issues apart from text select which I've explained above. It detects but doesn't select. I'm unsure if there are any permissions missing it anything. I tried multiple Android system intelligence Apks and none of them fix the issue.

Coming to flipendo, it works half way. What I meant to say is that you can now access the flipendo settings but clicking on it make changes causes it to crash. It used to crash the entire settings previously.

**Comment by sangeethps2255** [comment]
have you tried team files pixel launcher mod?

**Comment by nikhilmenghani** [comment]
@pixincreate can you try the latest build and let me know if 'select' feature works for you on los19.1?

**Comment by pixincreate** [comment]
I'll try today in the evening

**Comment by pixincreate** [comment]
**Update:**    
I flashed GApps Stock and unfortunately, it skipped some packages due to insufficient storage that had Pixel launcher included. So, as usual, I tried with my own config which I've mentioned above.   
Now, Pixel Launcher works as expected and the text select also works fine.   
Flipendo do work to some extent but crashes upon selecting `essential apps` and upon touching the notification that the app gives when the battery gets low. (and I don't think this depends upon other apps...)

**Comment by nikhilmenghani** [comment]
@pixincreate thanks for confirming, I was looking for an update on pixel launcher select feature only. I didn't touch flipendo. I'll close this issue since the original problem statement is resolved. Feel free to open a new one for other issues you encounter.

**Comment by pixincreate** [comment]
Thank you for the great work!

I'll open a separate issue for flipendo

**Comment by pixincreate** [comment]
Also, Pixel Launcher doesn't replace stock wallpaper app on Android.
LOS 19.1

**Comment by pixincreate** [comment]
Well, I flashed my phone today and guess what? Pixel launcher started to crash! Trying with July 9 Stock now.

**Comment by pixincreate** [comment]
I recently updated the canary and pixel launcher keeps stopping as trebuchet also exist along side

**Comment by nikhilmenghani** [comment]
@pixincreate https://github.com/nikhilmenghani/build/commit/ab80d7ed9bcc26eed41a52886d38f4565d7e6fd2 Next release will have this fixed.

**Comment by pixincreate** [comment]
I recently built the GApps and it is still crashing. The last working GApps for me is dated back to Aug 19 2022 with v22 config (Pixel launcher was not treated as an add-on).

**Comment by nikhilmenghani** [comment]
@pixincreate I'm working on a few things before I can look into it, it's on my list of priority.

**Comment by nikhilmenghani** [comment]
@pixincreate can you link me to the build that has working pixel launcher?

**Comment by pixincreate** [comment]
Config build: https://sourceforge.net/projects/nikgapps/files/Config-Releases/NikGapps-SL/19-Aug-2022/NikGapps-PiX-GApps-CLF-v1-arm64-12.1-20220819-signed.zip/download

**Comment by pixincreate** [comment]
This was the last working build. Since then, none of the builds have got pixel launcher working which forced me to make my own builds by cherry-picking apks and some extra apps like private compute services

**Comment by enzosanchezewe** [comment]
I had this issue, the problem was that i was installing android 12 gapps on 12.1.
I got confused because it says android 12 on device settings even when it's 12.1
In case anyone is having this issue you can check your api level with adb using this command
adb shell getprop ro.build.version.sdk
where api 31 = 12.0 and 32 = 12.1
You can also solve it temporaly by going to apkmirror and installing android 12.1 pixel launcher (you can access apps by pulling your quick panel > settings > apps > Chrome > Open)

**Comment by pixincreate** [comment]
> I had this issue, the problem was that i was installing android 12 gapps on 12.1. I got confused because it says android 12 on device settings even when it's 12.1 In case anyone is having this issue you can check your api level with adb using this command adb shell getprop ro.build.version.sdk where api 31 = 12.0 and 32 = 12.1 You can also solve it temporaly by going to apkmirror and installing android 12.1 pixel launcher (you can access apps by pulling your quick panel > settings > apps > Chrome > Open)

FYI, I've played with this a lot. Pixel launcher crashes on different scenarios and purposes. If it finds an ASI that it thinks isn't compatible, crashes, if it finds an incompatible Wallpaper, crashes. However, without ASI, launcher tends to work but text select doesn't. Without Google Wallpaper, launcher crashes uncontrollably.   

Since config v23, Launcher has been treated as an addon and not as a default app as any other apps such as browser / files. This IMO is the main reason behind crash. Using newer version of apps with newer code base on older config tends to work fine given that I use Aug 19 2022 pixel launcher builds.

**Comment by nikhilmenghani** [comment]
@pixincreate rephrasing my earlier statement to provide clarity
in your most recent pull request #5416 DevicePersonalizationServices=0 which is why when Pixel Launcher is installed, it's missing DPS.

can you please enable it and try again? I just tried flashing pixel launcher on android 13 and it's working fine, I will have to go through a lot of trouble flashing android 12.1, if you can do it, it would be great! Since it is working fine on a13, in theory it should work fine on a12.1 too, if it still doesn't work, I'll investigate further.

**Comment by pixincreate** [comment]
> @pixincreate rephrasing my earlier statement to provide clarity in your most recent pull request #5416 DevicePersonalizationServices=0 and GoogleWallpaper=0 which is why when Pixel Launcher is installed, it's missing DPS and wallpaper.
> 
> can you please enable it and try again? I just tried flashing pixel launcher on android 13 and it's working fine, I will have to go through a lot of trouble flashing android 12.1, if you can do it, it would be great! Since it is working fine on a13, in theory it should work fine on a12.1 too, if it still doesn't work, I'll investigate further.

I'll try once when the time permits, but ticking pixel launcher has wallpaper and system assistance within it right? I mean, the pixel launcher contains all of those, when I extracted the zip, pixel launcher had ASI and Wallpaper within it along with ASI and Wallpaper as separate zip outside as well..

**Comment by nikhilmenghani** [comment]
Even when PixelLauncher contains ASI, GoogleWallpaper, the config file reads 0 for both of them since the entry has it marked 0. I will make the changes with v24 to include those within PixelLauncher but for now, as long as you set DevicePersonalizationServices=1 and GoogleWallpaper=1 along side PixelLauncher=1, Pixel Launcher should not crash.

Let me know how it goes whenever you plan to flash again, if I flash it before you do, I'll let you know.

Or if @enzosanchezewe if you get a chance, please try above steps, it would help us get an update on where we're standing with pixel launcher.

**Comment by pixincreate** [comment]
So, I'll try by setting the values to 1 in config for #5416 in afzc.

**Comment by nikhilmenghani** [comment]
If you don't grant the permission, gms will spam with permission requests taking up more cpu and ram and in turn more battery.

And about the launcher, you're replacing both apks and config, in your tests to see if that's working, if you eliminate one of the options, we'd be able to narrow down if it was the apk that had an issue or the config.

**Comment by pixincreate** [comment]
> If you don't grant the permission, gms will spam with permission requests taking up more cpu and ram and in turn more battery.
It never asked for permission. Some apps like just crashed on signup just because I had not given GMS SMS permission. However, I was surprised to observe a different behaviour: Since the permissions(except PhysicalActivity, because greyed out) were removed, the device totally lagging, slow and unresponsive most of the times. I granted all the permissions once, everything started to work smoothly. I removed the permissions to check if it was really the issue, but not. It is still running smoothly except background app killing on some occasions..
> And about the launcher, you're replacing both apks and config, in your tests to see if that's working, if you eliminate one of the options, we'd be able to narrow down if it was the apk that had an issue or the config.

Yea, I had plans to do that, will do now..

**Comment by nikhilmenghani** [comment]
okay, I appreciate your efforts into testing these scenarios and reporting, I will take it over and try to fix it. Thank you!

**Comment by nikhilmenghani** [comment]
@pixincreate https://github.com/nikgapps/build/commit/8304cbf34ce11ef94de03e50f6918830688acdc1 :)

Next release!

**Comment by nikhilmenghani** [comment]
@pixincreate The changes are merged into stable branch and will reflect in the config build if you create one.

Once you are able to test it, let me know or close the issue.

**Comment by pixincreate** [comment]
- So the previous build that I did a day back had no changes? Isn't config builds are canary build based? 
- Does this launcher still have any compatibility issues? I wonder why still v23 is being used because, pixel launcher is still given the add-on position..

**Comment by nikhilmenghani** [comment]
Was your previous build before the commit timestamp or after? I bet it was before.

It works fine on Los 19.1 for me on vayu so you tell me if it doesn't work for you.

v23 is still being used because we have many things in pipeline that haven't made it to release and if i release a new version 24 now, soon enough I'll have to make another version release which isn't good for the end users. Besides, you know the workaround, set the available addons that are part of pixel launcher to 1 so we can wait a little before bumping up the version.

**Comment by pixincreate** [comment]
> Was your previous build before the commit timestamp or after? I think it was before.
> 
Previous build was built on 22 Jan 2023, yesterday..

> It works fine on Los 19.1 for me on vayu so you tell me if it doesn't work for you.
> 
And do you use To-Do by Microsoft? I'm not sure why it crashes the launcher upon clicking the widget.  It doesn't seem to happen on other launcher. If you use one, you can try it to confirm once..:)

> v23 is still being used because we have many things in pipeline that haven't made it to release and if i release a new version 24 now, soon enough I'll have to make another version release which isn't good for the end users. Besides, you know the workaround, set the available addons that are part of pixel launcher to 1 so we can wait a little before bumping up the version.  

Understandable, I usually add `privateComputeServices` along with `pixelCameraServices` into `system_ext` along with these modifications..😅
