### ISSUE TITLE
Flipendo doesn't work to the fullest

### ISSUE THREAD

**Issue by pixincreate** [nikgapps/config#3972]
Flipendo do work to some extent but crashes upon selecting essential apps and upon touching the notification that the app gives when the battery gets low. (and I don't think this depends upon other apps...)

**Comment by nikhilmenghani** [comment]
can you attach any kind of logs?

**Comment by pixincreate** [comment]
# Filtered Logcat
[logcat_07-09-2022_15-45-46.txt](https://github.com/nikgapps/config/files/9076256/logcat_07-09-2022_15-45-46.txt) 

# Unfiltered Logcat
[logcat_07-09-2022_15-46-10.txt](https://github.com/nikgapps/config/files/9076259/logcat_07-09-2022_15-46-10.txt)

**Comment by pixincreate** [comment]
https://github.com/reiryuki/Extreme-Battery-Saver-Magisk-Module

I'm attaching this link for the magisk module for your reference. According to this module, one needs to disable android signature verification for non-aosp signatured rom. I'm not sure whether this app require aosp signature to work or not if implementing through nikgapps. When I bundled the app manually, it didn't work .I had given ti all the necessary permissions (`android.permission.SUSPEND_APPS`)

**Comment by nikgapps** [comment]
Hi, can you test Flipendo if I attempt to fix it?

**Comment by pixincreate** [comment]
> Hi, can you test Flipendo if I attempt to fix it?

Umm, yes. But only during at night time (IST) on weekdays and anytime on weekends.
