### ISSUE TITLE
select feature still not working!!!

### ISSUE THREAD

**Issue by rahul6963** [nikgapps/config#4004]
still select feature isn't working after 9 july fixes , randomly showing android system intelligence service keep crashing, sir please fix it asap.^_____^

**Comment by nikhilmenghani** [comment]
It is tested on los19.1 and noted to be working fine, which Rom and device are you trying it on? Can you confirm on los19.1 if you're facing the issue?

**Comment by rahul6963** [comment]
dk sir with my april gapps pakage its working fine but with latest config pagake it wouldn't. it could be because of config version (my april pakage based on config 21 )or maybe problem with my rom (using VIOLET with superior os)

**Comment by rahul6963** [comment]
& markup also didn't working with latest pakage

**Comment by mihaizer** [comment]
> & markup also didn't working with latest pakage

Same. Murkup have version 9 and crashes. I tried to update by installing apk, by nikgapps add-on, by team-files magisk module and always got crash.

**Comment by nikhilmenghani** [comment]
Markup is fixed with latest release! for select feature, flash pixelify module.
