### ISSUE TITLE
google dialer  compatibility issue on playstore

### ISSUE THREAD

**Issue by saroj-nokia** [nikgapps/config#5592]
google dialer has  compatibility issue on playstore which makes unable to update it through playstore.
![Screenshot_20230122-182242_Google Play Store](https://user-images.githubusercontent.com/80759612/213916253-f5ecc06e-8ca1-4a88-9fb6-cc10565efbb9.png)

**Comment by nikhilmenghani** [comment]
@saroj-nokia android version?

**Comment by saroj-nokia** [comment]
i flash android 13 omni build

**Comment by nikhilmenghani** [comment]
I tested in my device, I cannot reproduce this issue, I am able to install/update google dialer (phone) on my oneplus 7 pro, los 20. Also, I see an uninstall option in the screenshot meaning at some point the app did go through playstore update. It is possible that you flashed a mod which conflicted with google dialer's compatibility on playstore. I suggest you to clean flash the device and see if you are able to reproduce it with just your rom and gapps.

**Comment by saroj-nokia** [comment]
i think it happen because of crdroid rom i used thanks for replay
