### ISSUE TITLE
devicepersonilizationservices addon

### ISSUE THREAD

**Issue by nikapos** [nikgapps/config#6462]
please provide the devicepersonilizationservices addon for the newer builds of nikgapps T. is there a reason i cannot find it in the downloads folder?

**Comment by nikhilmenghani** [comment]
You can configure nikgapps.config and flash pixel launcher addon, it has DPS.

**Comment by nikapos** [comment]
the thing is that crdroid 9.4 breaks with pixel launcher. let alone the fact that with pixel launcher i cannot remove the google search from my home screen..

**Comment by nikhilmenghani** [comment]
The thing is, this doesn't happen with Los and we don't modify pixel launcher apk, so the issue that you're experiencing is coming from the framework changes made to make stock launcher to work. On Crdroid, it is advisable to use stock launcher as it conflicts with pixel launcher in many ways.
