### ISSUE TITLE
elite request: creation of elite/13/alphadroid-davinci

### ISSUE THREAD

**Issue by helliscloser** [nikgapps/config#7962]
Hello there, 
This is Rumais. Been maintaining Alphadroid for Xiaomi Mi 9t/ k20. 
I would like to apply for  elite builds so that I can fianlly ship a streamlined gapps package for my users.
Though we ship both Vanilla & gapps variant, I myself use vanilla and been always recommending Nikgapps for Vanilla variant. 

My Rom releases are here:
https://forum.xda-developers.com/t/rom-official-13-0-alphadroid-1-7-9-davinci-04-aug-2023.4553447/

Official Sourceforge:
https://sourceforge.net/projects/alphadroid-project/files/davinci/

https://forum.xda-developers.com/t/rom-official-13-0-cherish-os-4-7-5-davinci-discontinued.4498621/
(Discontinued)

My Rom support group on telegram.
https://t.me/alphadroid_davinci

I might add more information if your really need more details to vaildate.

Thank you for NikGapps. It's the best.

**Comment by nikgapps** [comment]
Hi there, Thank you for recommending NikGapps. I've given you access to alphadroid_davinci folder. Feel free to send in a pull request by adding a config file to elite/13/alphadroid_davinci folder. Once your pull request is merged, you will find your builds shortly on https://nikgapps.com/helliscloser or you can also keep track of your builds [here](https://t.me/NikGappsGroup/185401).

**Comment by helliscloser** [comment]
Thanks for the response. But I don't see the folder. Or should i make it myself?

**Comment by nikhilmenghani** [comment]
@helliscloser Yes, you need to make one yourself while creating a pull request.

**Comment by helliscloser** [comment]
@nikhilmenghani Thanks for the assist. I made a pr. Along with a setup error I also got a message that I don't have access to alphadroid_davinci folder. Could you please kindly take a look?

**Comment by nikhilmenghani** [comment]
@helliscloser the folder you requested access for was alphadroid-davinci and the folder you uploaded file in was alphadroid_davinci. That's why you got that message. I've changed the folder name to alphadroid_davinci now and you should be able to upload you config.

**Comment by helliscloser** [comment]
Thank you.

**Comment by nikhilmenghani** [comment]
@helliscloser which android version nikgapps elites build are you using? android 13 or 14?

**Comment by helliscloser** [comment]
> @helliscloser which android version nikgapps elites build are you using? android 13 or 14?

A14. I'm yet to build qpr2 though. Is there something i can do?

**Comment by nikhilmenghani** [comment]
@helliscloser in preparation of android 15, I am deleting elite config for android 13, let me know if you still need it.

**Comment by helliscloser** [comment]
> @helliscloser in preparation of android 15, I am deleting elite config for android 13, let me know if you still need it.

Please go ahead, Won't need it. Thanks
