### ISSUE TITLE
Elite request: creation of elite/13/Juloboy 

### ISSUE THREAD

**Issue by Juloboy** [nikgapps/config#8173]
Hi, please add me to NikGapps Elites: <Juloboy>. Patreon monthly 2$ subscription.

**Comment by nikgapps** [comment]
@Juloboy you now have access to Juloboy folder, feel free to create a pull request after uploading your config file in elite/13/Juloboy folder. After the build is created, you will find the download link here - https://nikgapps.com/Juloboy

**Comment by nikhilmenghani** [comment]
@Juloboy which android version nikgapps elites build are you using? android 13 or 14?

**Comment by Juloboy** [comment]
I was using A13 in the past. Now I'm on stock A14 ROM of my new device. Hope to use Nikgapps Elite again later when stable A14 custom ROMs will be available for my phone.

**Comment by nikhilmenghani** [comment]
okay so I am removing this at the moment since you're not using it, re-open the issue and let me know once you need them.
