### ISSUE TITLE
Some features of Pixel Launcher are not working properly

### ISSUE THREAD

**Issue by Endergreen12** [nikgapps/config#8282]
I'm sorry if it's not a problem on Gapps' side

Google search predictions under Pixel Launcher don't look right when dark theme Displays correctly when using white theme

![Screenshot_20230830-180336_Pixel Launcher.png](https://github.com/nikgapps/config/assets/90076182/e14ba0d7-f11f-436e-a697-2b7880dc52c3)

Battery widget is not working properly 
It will not update as it will show "Loading"
After restarting, it works normally for a while, but after a while it stops working again

![Screenshot_20230830-180338_Pixel Launcher~2.png](https://github.com/nikgapps/config/assets/90076182/f830fe27-043b-4205-914a-6fa79da3c157)

Variants: Full
OS: Crdroid 9.8

I would appreciate it if you could fix these problems

**Comment by nikgapps** [comment]
Hi @Endergreen12, these are known issues and we're working on fixing it. 

1st one is specific to Rom and doesn't happen on LOS, the 2nd one is known but we're actively looking for it's solution.

**Comment by Endergreen12** [comment]
> Hi @Endergreen12, these are known issues and we're working on fixing it. 
> 
> 1st one is specific to Rom and doesn't happen on LOS, the 2nd one is known but we're actively looking for it's solution.

thank you for your reply
hope you find a solution
i wish you the best!
