### ISSUE TITLE
[Idea] Update README.md

### ISSUE THREAD

**Issue by ameyagokhale** [nikgapps/config#84]
Hello team,

My Idea is to simplify and mention some points in README so that issues issue like deleting/renaming files do not occur.

Sample changes I am thinking of: https://github.com/ameyagokhale/config/blob/update_readme/README.md

**Comment by nikhilmenghani** [comment]
Hi,

As discussed, please send a PR with the changes in readme.md and I'll merge them. 

Thanks,
Nikhil
