### ISSUE TITLE
Hi, please add me to NikGapps Elites:UMR85N

### ISSUE THREAD

**Issue by Dreamer-Arcana** [nikgapps/config#8411]

**Comment by nikgapps** [comment]
Closing this issue as access is provided

**Comment by nikhilmenghani** [comment]
@Dreamer-Arcana which android version nikgapps elites build are you using? android 13 or 14?

**Comment by nikhilmenghani** [comment]
@Dreamer-Arcana in preparation of android 15, I am deleting elite config for android 13, let me know if you still need it.
