### ISSUE TITLE
Elite request: Add pfuenzle

### ISSUE THREAD

**Issue by Pfuenzle** [nikgapps/config#8615]
Hi, I'm a sponsor on GitHub, would be great if I could get access to "elite/<ver>/pfuenzle/".
Thanks a lot :)

**Comment by nikhilmenghani** [comment]
Hi @Pfuenzle, thank you for your contribution. Access has been provided, please proceed ahead with creating a new pull request. Upload your config in elite/13/pfuenzle folder and you will get your first elite build shortly.

**Comment by Pfuenzle** [comment]
Thanks a lot :)

**Comment by nikhilmenghani** [comment]
@Pfuenzle which android version nikgapps elites build are you using? android 13 or 14?

**Comment by nikhilmenghani** [comment]
@Pfuenzle in preparation of android 15, I am deleting elite config for android 13, let me know if you still need it.
