### ISSUE TITLE
elite request: android-13/crDroid-alioth/

### ISSUE THREAD

**Issue by peter4vn** [nikgapps/config#8674]
Hello

I m not very good with words.
I did a small donation to nikgapps and i got a link about the elites.
I followed the steps and here i am.
I dont know if i should provide any additional info, let me know.

Love your work.

**Comment by nikhilmenghani** [comment]
@peter4vn thank you for the donation, you need to confirm the folder name in which you'd like your elite builds be created. I will provide you access to that folder and then you need to send a pull request with your nikgapps.config and a new elite build will be created for you. Please feel free to send me a message on telegram @iNikhilMenghani if you have questions.

**Comment by peter4vn** [comment]
Folder name : 
peter4vn

**Comment by nikhilmenghani** [comment]
@peter4vn access has been provided, please proceed with your pull request under elite/13/peter4vn folder and you'll have the Elite builds created for you.

**Comment by nikhilmenghani** [comment]
@peter4vn which android version nikgapps elites build are you using? android 13 or 14?

**Comment by peter4vn** [comment]
Sorry for replying so late.
To be honest i never used nikgapps elites build.
I m going to flash android 14 soon.

**Comment by nikhilmenghani** [comment]
@peter4vn reopen this issue when you need an elite build
