### ISSUE TITLE
[BUG] NikGapps system update problem

### ISSUE THREAD

**Issue by onurbbr** [nikgapps/config#8925]
I am using crDroid 9.10. I updated to version 9.11, but Google Play Services keeps giving errors and crDroid's system applications have been restored. Normally, these applications were automatically removed in OpenGapps, but this is not available in NikGapps. Google Applications are installed, but system applications are not removed. (Although applications such as Google Messages, Google Dialer, Google Chrome should remove applications such as Dialer, Messenger and Browser, this does not happen with the ROM update.)

**Comment by nikhilmenghani** [comment]
do you see logs generated in /sdcard/NikGapps folder? there should be a folder named addonlogs, can you zip the NikGapps folder and upload it here?

**Comment by jason-eu** [comment]
> I am using crDroid 9.10. I updated to version 9.11, but Google Play Services keeps giving errors and crDroid's system applications have been restored. Normally, these applications were automatically removed in OpenGapps, but this is not available in NikGapps. Google Applications are installed, but system applications are not removed. (Although applications such as Google Messages, Google Dialer, Google Chrome should remove applications such as Dialer, Messenger and Browser, this does not happen with the ROM update.)

What device and ROM ?
What was the package variant and Android version used ?
Was a NikGApps config file used ?
Was `execute.d=1` set to `execute.d=0`?

**Comment by nikhilmenghani** [comment]
Closing since no response
