### ISSUE TITLE
Elite folder

### ISSUE THREAD

**Issue by a2zshahriar** [nikgapps/config#9022]
Add me to NikGapps Elites: <srh>

**Comment by nikhilmenghani** [comment]
Hi there, you need to contribute in one of the listed ways in this link - https://nikgapps.com/misc/2023/06/08/NikGapps-Elites.html#how-to-join-nikgapps-elites before you can be enrolled for NikGapps Elites

**Comment by nikhilmenghani** [comment]
closing since there is no response on the thread
