### ISSUE TITLE
ellite request folder name: m3lindr0s0

### ISSUE THREAD

**Issue by melindr0s0** [nikgapps/config#9547]
Hi there, I just became a donor and l'd like to be an elite member. Thanks for making Nikgapps the best choice we can use

**Comment by nikhilmenghani** [comment]
@melindr0s0 can you specify the name of the folder you'd like your builds be part of?

**Comment by NikGappsOfficial** [comment]
Closing the issue as the builds are ready https://nikgapps.com/melindr0s0

**Comment by nikhilmenghani** [comment]
https://nikgapps.com/melindr0s0

closing this since the builds are ready.

**Comment by nikhilmenghani** [comment]
@melindr0s0 which android version nikgapps elites build are you using? android 13 or 14?

**Comment by melindr0s0** [comment]
> @melindr0s0 which android version nikgapps elites build are you using? android 13 or 14?

I'm using Android 14
