### ISSUE TITLE
Updated packages whenever customized gapps are built

### ISSUE THREAD

**Issue by Subhashis2007** [nikgapps/config#9673]
If I am not wrong, nikgapps customized versions carry the last updated gapps i.e., same version as officially released gapps, but it would be nicer if the gapps are all up to the date when the customized version of gapps is built

**Comment by nikhilmenghani** [comment]
The reason why the apk updates are not offered is to provide stability on user builds. The apks are required to be tested before release so users don't get into trouble. I could still try and find a way to make test builds.

**Comment by Subhashis2007** [comment]
ohh

**Comment by nikhilmenghani** [comment]
Unfortunately, this is not possible at the moment. let me know if we are good to close this issue.
