### ISSUE TITLE
Elite Request

### ISSUE THREAD

**Issue by CanerKaraca23** [nikgapps/config#9763]
Hi, i was contributed to project, here: https://github.com/nikgapps/project/pull/3

Is it counting as contributor for elite?

**Comment by nikhilmenghani** [comment]
Absolutely, please provide the folder name and android version you'd like access to.

**Comment by CanerKaraca23** [comment]
> Absolutely, please provide the folder name and android version you'd like access to.

Thanks, folder name CanerKaraca, Android 14.

**Comment by nikhilmenghani** [comment]
@CanerKaraca23 you now have access to the folder, please create a pull request under elite/14/CanerKaraca/<yourconfiggoeshere>

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 you now have access to the folder, please create a pull request under elite/14/CanerKaraca/

I've created, thank you very much.

**Comment by nikhilmenghani** [comment]
@CanerKaraca23 which android version nikgapps elites build are you using? android 13 or 14?

**Comment by CanerKaraca23** [comment]
@nikhilmenghani Can i create Android 15 builds?

**Comment by nikhilmenghani** [comment]
@CanerKaraca23 yes, you already have access. Please go ahead and upload a new config in your elite folder. Also, please delete the previous one if you're not using.
