### ISSUE TITLE
Prateek Gurjar

### ISSUE THREAD

**Issue by DeadlyShroud** [nikgapps/config#9974]
Request for including in NikGApps Elite!
Hi Nik, I have been using NikGApps since long. I always compile and use Vanilla ROMs, for me GApps = NikGApps. I not only create custom builds for myself but also share them in the community and they too use those builds. I also compile ROMs and always recommend NikGApps for the same.
References:
1. https://telegram.me/PocoF4updates/746
2. https://telegram.me/PocoF4updates/766
Thanks a lot for your work!

**Comment by nikhilmenghani** [comment]
@DeadlyShroud what is the name of the folder you need to create your elite builds in?

**Comment by DeadlyShroud** [comment]
> @DeadlyShroud what is the name of the folder you need to create your elite builds in?

Folder Name - PrateekGurjar

**Comment by nikhilmenghani** [comment]
@DeadlyShroud done, create a pull request in elite/<android_version>/PrateekGurjar/<your config here>
